# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Dropbox\dev\Python\GenCard\wi.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dialog(object):
    def setupUi(self, dialog):
        dialog.setObjectName("dialog")
        dialog.resize(609, 409)
        self.label_5 = QtWidgets.QLabel(dialog)
        self.label_5.setGeometry(QtCore.QRect(7, 147, 141, 16))
        self.label_5.setObjectName("label_5")
        self.pushButton_4 = QtWidgets.QPushButton(dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(460, 340, 121, 41))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_4 = QtWidgets.QLabel(dialog)
        self.label_4.setGeometry(QtCore.QRect(377, 147, 71, 16))
        self.label_4.setObjectName("label_4")
        self.comboBox = QtWidgets.QComboBox(dialog)
        self.comboBox.setGeometry(QtCore.QRect(367, 167, 161, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox_2 = QtWidgets.QComboBox(dialog)
        self.comboBox_2.setGeometry(QtCore.QRect(7, 117, 271, 21))
        self.comboBox_2.setObjectName("comboBox_2")
        self.pushButton = QtWidgets.QPushButton(dialog)
        self.pushButton.setGeometry(QtCore.QRect(10, 70, 191, 20))
        self.pushButton.setObjectName("pushButton")
        self.comboBox_3 = QtWidgets.QComboBox(dialog)
        self.comboBox_3.setGeometry(QtCore.QRect(297, 117, 251, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.pushButton_2 = QtWidgets.QPushButton(dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 30, 191, 20))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_3 = QtWidgets.QLabel(dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 100, 141, 16))
        self.label_3.setObjectName("label_3")
        self.checkBox = QtWidgets.QCheckBox(dialog)
        self.checkBox.setGeometry(QtCore.QRect(367, 207, 101, 17))
        self.checkBox.setObjectName("checkBox")
        self.label_7 = QtWidgets.QLabel(dialog)
        self.label_7.setGeometry(QtCore.QRect(297, 97, 241, 16))
        self.label_7.setObjectName("label_7")
        self.lineEdit_4 = QtWidgets.QLineEdit(dialog)
        self.lineEdit_4.setGeometry(QtCore.QRect(7, 167, 321, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.progressBar = QtWidgets.QProgressBar(dialog)
        self.progressBar.setGeometry(QtCore.QRect(370, 300, 221, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.label_2 = QtWidgets.QLabel(dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 161, 20))
        self.label_2.setObjectName("label_2")
        self.label_6 = QtWidgets.QLabel(dialog)
        self.label_6.setGeometry(QtCore.QRect(7, 187, 311, 16))
        self.label_6.setObjectName("label_6")
        self.label = QtWidgets.QLabel(dialog)
        self.label.setGeometry(QtCore.QRect(20, 10, 141, 20))
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(dialog)
        self.textEdit.setGeometry(QtCore.QRect(10, 210, 321, 161))
        self.textEdit.setObjectName("textEdit")
        self.toolButton = QtWidgets.QToolButton(dialog)
        self.toolButton.setGeometry(QtCore.QRect(210, 30, 25, 19))
        self.toolButton.setObjectName("toolButton")
        self.toolButton_2 = QtWidgets.QToolButton(dialog)
        self.toolButton_2.setGeometry(QtCore.QRect(210, 70, 25, 19))
        self.toolButton_2.setObjectName("toolButton_2")
        self.comboBox_4 = QtWidgets.QComboBox(dialog)
        self.comboBox_4.setGeometry(QtCore.QRect(370, 250, 161, 22))
        self.comboBox_4.setObjectName("comboBox_4")

        self.retranslateUi(dialog)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslateUi(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("dialog", "Генератор карт "))
        self.label_5.setText(_translate("dialog", "Одно слово"))
        self.pushButton_4.setText(_translate("dialog", "Генерировать"))
        self.label_4.setText(_translate("dialog", "Язык"))
        self.comboBox.setToolTip(_translate("dialog", "<html><head/><body><p>Выбор языка</p></body></html>"))
        self.comboBox.setWhatsThis(_translate("dialog", "<html><head/><body><p>Выбор языка</p></body></html>"))
        self.pushButton.setText(_translate("dialog", "..."))
        self.pushButton_2.setText(_translate("dialog", "..."))
        self.label_3.setText(_translate("dialog", "Колода"))
        self.checkBox.setText(_translate("dialog", "Скачивать mp3"))
        self.label_7.setText(_translate("dialog", "Шаблон"))
        self.label_2.setText(_translate("dialog", "Импорт из текстого файла"))
        self.label_6.setText(_translate("dialog", "Слова не найденые в словаре"))
        self.label.setText(_translate("dialog", "Импорт из Kindle "))
        self.toolButton.setText(_translate("dialog", "X"))
        self.toolButton_2.setText(_translate("dialog", "X"))
        self.comboBox_4.setToolTip(_translate("dialog", "<html><head/><body><p>Выбор языка</p></body></html>"))
        self.comboBox_4.setWhatsThis(_translate("dialog", "<html><head/><body><p>Выбор языка</p></body></html>"))

